require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-clock/0.21.15/killbill-clock-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/zaxxer/HikariCP-java6/2.3.13/HikariCP-java6-2.3.13.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-api/0.51.27/killbill-api-0.51.27.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.6.7/jackson-dataformat-csv-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/skife/config/config-magic/0.17/config-magic-0.17.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/weakref/jmxutils/1.19/jmxutils-1.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/aopalliance/aopalliance/1.0/aopalliance-1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/osgi/org.osgi.core/5.0.0/org.osgi.core-5.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/ning/async-http-client/1.9.40/async-http-client-1.9.40.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-platform-osgi/0.37.19/killbill-platform-osgi-0.37.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/jline/jline/2.14.6/jline-2.14.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-internal-api/0.19.18/killbill-internal-api-0.19.18.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/kafka/kafka-clients/2.3.0/kafka-clients-2.3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/joda/joda-money/0.9/joda-money-0.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ehcache/integrations/shiro/shiro-ehcache3/1.0.0/shiro-ehcache3-1.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-concurrent/0.21.15/killbill-concurrent-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-util/0.19.18/killbill-util-0.19.18.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/dataformat/jackson-dataformat-smile/2.6.7/jackson-dataformat-smile-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/jcl-over-slf4j/1.7.25/jcl-over-slf4j-1.7.25.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/jasypt/jasypt/1.9.2/jasypt-1.9.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/inject/guice/3.0/guice-3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-platform-api/0.37.19/killbill-platform-api-0.37.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/netty/netty/3.10.6.Final/netty-3.10.6.Final.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/felix/org.apache.felix.framework/4.4.1/org.apache.felix.framework-4.4.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ehcache/ehcache-clustered/3.3.1/ehcache-clustered-3.3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-util/0.19.18/killbill-util-0.19.18-tests.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/guava/guava/20.0/guava-20.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/samskivert/jmustache/1.5/jmustache-1.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-platform-lifecycle/0.37.19/killbill-platform-lifecycle-0.37.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-currency/0.24.8/killbill-plugin-api-currency-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-entitlement/0.24.8/killbill-plugin-api-entitlement-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/cache/cache-api/1.0.0/cache-api-1.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/bgee/log4jdbc-log4j2/log4jdbc-log4j2-jdbc4/1.16/log4jdbc-log4j2-jdbc4-1.16.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-annotations/2.6.7/jackson-annotations-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/shiro/shiro-core/1.3.2/shiro-core-1.3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-databind/2.6.7/jackson-databind-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/code/findbugs/annotations/3.0.1u2/annotations-3.0.1u2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-invoice/0.24.8/killbill-plugin-api-invoice-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-notification/0.24.8/killbill-plugin-api-notification-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-payment/0.24.8/killbill-plugin-api-payment-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/antlr/ST4/4.0.8/ST4-4.0.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/shiro/shiro-guice/1.3.2/shiro-guice-1.3.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-locker/0.21.15/killbill-locker-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/ehcache/ehcache/3.3.1/ehcache-3.3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/lz4/lz4-java/1.6.0/lz4-java-1.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-jcache/3.2.2/metrics-jcache-3.2.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.6.7/jackson-datatype-joda-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/inject/extensions/guice-multibindings/3.0/guice-multibindings-3.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/inject/javax.inject/1/javax.inject-1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/h2database/h2/1.4.194/h2-1.4.194.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/fasterxml/jackson/core/jackson-core/2.6.7/jackson-core-2.6.7.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-jdbi/0.21.15/killbill-jdbi-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/cglib/cglib/3.1/cglib-3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/dropwizard/metrics/metrics-core/3.2.2/metrics-core-3.2.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-embeddeddb-common/0.21.15/killbill-embeddeddb-common-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-platform-base/0.37.19/killbill-platform-base-0.37.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-queue/0.21.15/killbill-queue-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/github/luben/zstd-jni/1.4.2-1/zstd-jni-1.4.2-1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/killbill-platform-osgi-api/0.37.19/killbill-platform-osgi-api-0.37.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/commons/killbill-xmlloader/0.21.15/killbill-xmlloader-0.21.15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/mockito/mockito-all/1.10.19/mockito-all-1.10.19.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-control/0.24.8/killbill-plugin-api-control-0.24.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/osgi/org.osgi.compendium/5.0.0/org.osgi.compendium-5.0.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/kill-bill/billing/plugin/killbill-plugin-api-catalog/0.24.8/killbill-plugin-api-catalog-0.24.8.jar')
JBUNDLER_CLASSPATH.freeze
